### ISSUE TITLE
Implement API route to return all "Experiences"

### ISSUE THREAD

**Issue by MLHProgram** [MLH-Fellowship/orientation-project-python-24.FAL.A#21]
On the `/resume/experience` route, you should:

- [ ] Return the Experience list when a GET request is made. The return should be in a list format.

**Comment by dannyl1u** [comment]
I'll work on this

**Comment by dannyl1u** [comment]
@davidkurilla would you like to take this one as well since #24 which you're working on uses the same route

**Comment by Pradyuman7** [comment]
So, who's up for this one finally?

**Comment by davidkurilla** [comment]
I can do that one! Thanks @dannyl1u
